### ISSUE TITLE
Data race-unsafe use of package-level variables

### ISSUE THREAD

**Issue by blocknonip** [bwmarrin/snowflake#15]
Global package-level variables are being used unsafely from the perspective of the race detector. For example, trying to use `NewNode()` and `Generate()` at the same time will trip the race detector for `nodeShift` in:

```
snowflake/snowflake.go:97
snowflake/snowflake.go:132
```

Steps to reproduce:
- Run `NewNode()` and `Generate()` in parallel, such as via tests using `t.Parallel()`.
- Use race detector when running tests.

Other package-level variables besides `nodeShift` may also affected.

**Comment by bwmarrin** [comment]
Thanks for the information, I'll review it.

**Comment by bwmarrin** [comment]
@blocknonip it's been awhile, but I've got some time to care for my github packages :)

I'm working on a solution to this issue and I can see where a data race would happen just by looking at the code.  I tried to write a test that would showcase it using t.Parallel() however so far I've been unsuccessful.  Any change you can provide an example test that would cause the race detector to complain?

**Comment by blocknonip** [comment]
Thanks, looks great!
