### ISSUE TITLE
Support decode id

### ISSUE THREAD

**Issue by axetroy** [bwmarrin/snowflake#22]
```go
func DecodeString (id string) (*Node, error) {
  // decode
}
```

**Comment by bwmarrin** [comment]
Can you give me some more context of what you're wanting?

**Comment by axetroy** [comment]
In some cases, we only have ID string

But we need to know which node this ID was generated from and when

**Comment by bwmarrin** [comment]
What format is the ID in though.  "string" is a bit ambiguous.   

Is it a string of numbers like "8217397129123" or some other format?

Have you tried using https://github.com/bwmarrin/snowflake/blob/master/snowflake.go#L169 ?
If it's a string of numbers, you can convert that into an int64 easily enough, then parse it with that function.  After doing that, you can use the library to return the node.

**Comment by axetroy** [comment]
@bwmarrin I see. Thx.
