### ISSUE TITLE
Why don't we use the method init() anywhere?

### ISSUE THREAD

**Issue by khiem111189** [bwmarrin/snowflake#27]
May I ask why don't we use the method init() anywhere?

https://github.com/bwmarrin/snowflake/blob/c09e69ae59935edf6d85799e858c26de86b04cb3/snowflake.go#L59

**Comment by bwmarrin** [comment]
init() is a magic function of sorts that Go uses on it's own.  That function is called by the go runtime when the application launches.  It just does some basic **init**ialization that needs to be done.
