### ISSUE TITLE
How can i reduce the length of id?

### ISSUE THREAD

**Issue by jonathanchoo519** [bwmarrin/snowflake#29]
Hi

I generate ids by default setting got the length is 19, how can i reduce the length down to 15?

thx

**Comment by vkstack** [comment]
this gives you 64 bit number,
There is no way you can short this, unless you write your own.

if you convert it to base62 you ll have a shorter id for sure

**Comment by bwmarrin** [comment]
There are several methods in this package you can use to reduce the number of characters an ID uses.  Like the Base58 method here, https://github.com/bwmarrin/snowflake/blob/master/snowflake.go#L250.
