### ISSUE TITLE
生成的ID会重复

### ISSUE THREAD

**Issue by mztlive** [bwmarrin/snowflake#39]
func NextIdentity() (int64, error) {
	//TODO: NodeID 换成读取配置
	node, err := snowflake.NewNode(1)

	if err != nil {
		Logger().Info(
			"Generate identity fail.",
			zap.String("error", err.Error()),
		)
	}

	ID := node.Generate()
	return ID.Int64(), nil
}

r.GET("/testOrder", func(c *gin.Context) {
		fmt.Println(utils.NextIdentity())
}

ab -c 10 -n 11 http://localhost:8080/testOrder

就在10个并发的时候就会重复

**Comment by zhangyi176** [comment]
snowflake.NewNode(1) 这部分要提前完成，仅在程序启动时初始化一次，后面再使用node.Generate()。

**Comment by 54huige** [comment]
用单例模式吧

**Comment by alaywn** [comment]
> 用单例模式吧

怎么算单例模式？启动服务的全局初始化一次snowflake.NewNode么？

**Comment by CarsonSlovoka** [comment]
有點驚訝，issues不多，但是光用中文下標題的就佔兩個了，是因為作者群裡面有人看得懂中文還是圖方便就用中文問而已?

----

另外我覺得2樓已經給了解答，因此這個issues可以考慮關閉了

> snowflake.NewNode(1) 这部分要提前完成，仅在程序启动时初始化一次，后面再使用node.Generate()。

**Comment by CarsonSlovoka** [comment]
> > 用单例模式吧
> 
> 怎么算单例模式？启动服务的全局初始化一次snowflake.NewNode么？

```go
n := snowflake.NewNode(1)
n.Generate()
n.Generate()
n.Generate()
```

而不可以
```go
```go
n := snowflake.NewNode(1)
n.Generate()
n = snowflake.NewNode(1)
n.Generate()
```
如果不斷產生Node的新對象，這樣有Lock等於沒Lock，可以看一下[代碼](https://github.com/bwmarrin/snowflake/blob/7511dd2b95883fdcd3fd35494451124fdc9b06cb/snowflake.go#L135-L137)
```

**Comment by bwmarrin** [comment]
> 有點驚訝，issues不多，但是光用中文下標題的就佔兩個了，是因為作者群裡面有人看得懂中文還是圖方便就用中文問而已?


Thanks for helping on this issue.  Because I'm over here using Google Translate to try to understand what any of this says :)

Definitely no authors (only me) that understands Chinese.
