### ISSUE TITLE
生成得id都是偶数

### ISSUE THREAD

**Issue by pwh19920920** [bwmarrin/snowflake#40]
低并发情况下末尾重置为0，不便于取余使用问题，建议做个开关判断一下

**Comment by CarsonSlovoka** [comment]
我覺得標題不當，我對你內文的理解是:

> 因為你生成的資料都是末尾為0，所以你不需要末尾的那些數字 (反正都是0)

所以這跟偶數比較無關。另外`不便於使用`應該是`不需要`的意思?

總之末尾表示`流水號`，是在毫秒相同的情況下，所衍伸出來的東西，

如果低併發的時間間格都很長，那麼我建議您可以[調整StepBits](https://github.com/bwmarrin/snowflake/blob/7511dd2b95883fdcd3fd35494451124fdc9b06cb/snowflake.go#L23-L25)

你可以把數值改低一點
