### ISSUE TITLE
Why do we need the nodeMax?

### ISSUE THREAD

**Issue by CarsonSlovoka** [bwmarrin/snowflake#46]
[nodeMax](https://github.com/bwmarrin/snowflake/blob/3cf6d89d1fe90688e862739ec26be74ebef77a57/snowflake.go#L87) seems to be generated only to determine [whether the given `node` is reasonable](https://github.com/bwmarrin/snowflake/blob/3cf6d89d1fe90688e862739ec26be74ebef77a57/snowflake.go#L120-L122), so should we consider removing it from the [structure](https://github.com/bwmarrin/snowflake/blob/3cf6d89d1fe90688e862739ec26be74ebef77a57/snowflake.go#L80-L92)?

**Comment by bwmarrin** [comment]
So are you saying that instead of using nodeMax value we could just do the calculation at the time we do the check that the node size is valid?  Or are you thinking something else?

Does having the nodeMax value cause some sort of issue?

**Comment by CarsonSlovoka** [comment]
> Does having the nodeMax value cause some sort of issue?

nodeMax works well.

----

I just thought about whether to let the structure become simple

When I see a structure with many attributes, I will need to read many things, reducing my desire to read further. 😅

```go
	n := Node{}
	n.node = node
	// n.nodeMax = -1 ^ (-1 << NodeBits)
	nodeMax := -1 ^ (-1 << NodeBits)
	n.nodeMask = n.nodeMax << StepBits
	n.stepMask = -1 ^ (-1 << StepBits)
	n.timeShift = NodeBits + StepBits
	n.nodeShift = StepBits

	// if n.node < 0 || n.node > n.nodeMax {
	if n.node < 0 || n.node > nodeMax {
		return nil, errors.New("Node number must be between 0 and " + strconv.FormatInt(n.nodeMax, 10))
	}
```

Yes, this opinion is subjective

**Comment by bwmarrin** [comment]
Not a bad idea actually :)  I like simple too.  We could move this into a local var in the function and keep the struct smaller.
