### ISSUE TITLE
Add parsers

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/snowflake#6]
We've got many methods to convert a snowflake into different formats but no methods to convert from those formats back into a snowflake.   There should be a 1:1 pair for all formats.

**Comment by dxvgef** [comment]
I also need this feature.

**Comment by bwmarrin** [comment]
Caught me at a good time - I've been finding time to care for my libs lately :)  I'll be looking into adding some soon, I hope.

**Comment by dxvgef** [comment]
@bwmarrin 👍

**Comment by dxvgef** [comment]
I saw that the new parser is only converted to int64 type. Can I export the `snowflake.Node` and `snowflake.Epoch` information based on int64?

**Comment by bwmarrin** [comment]
Node, Time, and Epoch funcs need changed, as they are actually deprecated in their current form.  I'll work on those soon.

But you can use them as they are now by converting whatever item into an ID then using the Node/Epoch/Time functions on that ID to get that info out.  You'll have to make sure the Epoch is set correctly if you're using custom value.

If you give me an example of what you're trying to do, I can help you better.
